config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  # for posts
  resources :posts do
    collection do
      get :upload_csv
      post :import_csv
      get :download
      get :search, to: 'posts#search'
    end
    member do
      post :update_post
    end
  end

  # for users
  resources :users do
    collection do
      get :search, to: 'users#search'
    end
    member do
    end
  end

  # for login
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#log_out'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  # for password reset
  get 'password/:id', to: 'passwords#edit', as: 'edit_password'
  post 'password/:id', to: 'passwords#update'

  get 'reset/password', to: 'passwords#new'
  post 'reset/password', to: 'passwords#create'
  get 'reset/password/edit', to: 'passwords#editReset'
  patch 'reset/password/edit', to: 'passwords#updateReset'
end

app/views/layouts/_alerts.html.slim
.alert.alert-dismissible.fade.show.bg-dark.blue role="alert"
  = notice
  button.close type="button" data-dismiss="alert" aria-label="Close"
    span aria-hidden="true" ="&times".html_safe

app/views/layouts/_footer.html.slim
footer 
  .footer.text-center.py-3.bg-dark
    a href="http://seattleconsultingmyanmar.com/en" class="text-light" Seattle Consulting Myanmar Co.,Ltd. All rights reserved. © Copyright

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-dark.text-light
  = link_to "OJT", root_path , class:"navbar-brand text-light"
  .collapse.navbar-collapse id="navbarSupportedContent"
    -if logged_in?
      ul.navbar-nav.mr-auto
        -if admin?
          li.nav-item
            = link_to "User List", users_path , class:"nav-link text-light"
        li.nav-item 
          = link_to "Post List", posts_path , class:"nav-link text-light"
      ul.navbar-nav.my-sm-0
        -if admin?
          li.nav-item
            = link_to "Create User", new_user_path , class:"nav-link text-light"
        li.nav-item 
          .dropdown.show
            a.nav-link.dropdown-toggle.text-light role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
              = current_user.name
            .dropdown-menu aria-labelledby="dropdownMenuLink" style="left:-75px;"
              = link_to "Profile", user_path(current_user) , class:"dropdown-item"
              = link_to "Log Out", logout_path , class:"dropdown-item"
          

app/views/layouts/application.html.slim
doctype html
html
  head
    title OJT
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    / / Bootstrap CSS & JS Library
    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"
    = stylesheet_link_tag  'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css'

        / / Datatable
    = stylesheet_link_tag  'https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css'
    = stylesheet_link_tag  'https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js'
    script src= "https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js" 
    
    / / Custom CSS
    = stylesheet_link_tag  "common"

 
  body
    -if logged_in?
      = render 'layouts/header'  
    -if notice 
      = render 'layouts/alerts'  
    .wrapper
      = yield 
    -if logged_in? 
      = render 'layouts/footer'

javascript:
 $(document).ready( function () {
     var table = $('#table_id').DataTable({
    "bStateSave": true,
    "bInfo" : false,
    "searching": false,
    dom: '<"top"i>rt<"bottom"flp><"clear">',
    });

 });